In [83]:
import httpx
import os
import sys
import json
import pandas as pd

sys.path.append(os.path.abspath('./src'))
from db_functions import DotaDB
opendota_url = 'https://api.opendota.com/api'
db = DotaDB()

In [ ]:
result = httpx.get(f'{opendota_url}/live').json()
pro_matches = []
for r in result:
    if r['league_id'] != 0:
        pro_matches.append(r)
pd.DataFrame(pro_matches).iloc[:, :15]

,activate_time,deactivate_time,server_steam_id,lobby_id,league_id,lobby_type,game_time,delay,spectators,game_mode,average_mmr,match_id,series_id,team_name_radiant,team_name_dire
0,1774853855,0,90283662945047562,29773684374794677,18867,1,1446,120,1,2,0,8750122430,1080822,Nethercore,Teiko
1,1774856366,1774859770,90283667901656075,29773684396987958,18867,1,2732,120,1,2,0,8750150836,1080822,Nethercore,Teiko
2,1774858358,1774861044,90283661343804435,29773684403631623,19255,1,1783,900,12,2,0,8750161286,1080836,_PowerRangers,VP.Prodigy
3,1774859737,1774863705,90283666646696979,29773684416754826,19520,1,3083,900,19,2,0,8750183428,1080838,NGNB,GreenTeaWatch
4,1774860558,0,90283667755473943,29773684430915901,18867,1,-49,120,1,2,0,8750203717,1080845,Teiko,Shinigami Gaming
5,1774861662,1774863783,90283661106707479,29773684447463007,18867,1,1938,120,2,1,0,8750218681,1080848,Teiko,Shinigami Gaming
6,1774864246,0,90283668738875421,29773684463252089,19520,1,1278,900,12,2,0,8750240751,1080838,NGNB,GreenTeaWatch
7,1774863949,0,90283669218320403,29773684470466339,18867,1,592,120,1,2,0,8750249409,1080848,Shinigami Gaming,Teiko

In [ ]:
with httpx.Client(headers=db.stratz_headers) as client:
    query = '''
    query($id: Long!) {
        match(id: $id) {
            id 
            startDateTime
        }
    }
    '''
    result = db.query_stratz(client, query, variables={'id': 8757271594})

In [ ]:
result

{'data': {'match': {'id': 8757271594, 'startDateTime': 1775305743}}}

In [85]:
with httpx.Client() as client:
    result = db.query_opendota(client, endpoint=f'matches/{8760126026}')

In [86]:
result

{'version': 22,
 'match_id': 8760126026,
 'teamfights': [{'start': 318,
   'end': 360,
   'last_death': 345,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'weaver_shukuchi': 3, 'weaver_the_swarm': 1},
     'ability_targets': {},
     'item_uses': {'madstone_bundle': 1, 'faerie_fire': 1, 'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 454,
     'healing': 421,
     'gold_delta': 224,
     'xp_delta': 492,
     'xp_start': 1309,
     'xp_end': 1801},
    {'deaths_pos': {'126': {'128': 1}},
     'ability_uses': {'huskar_inner_fire': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1, 'magic_stick': 1, 'faerie_fire': 1},
     'killed': {'npc_dota_hero_death_prophet': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1177,
     'healing': 115,
     'gold_delta': 394,
     'xp_delta': 126,
     'xp_start': 2243,
     'xp_end': 2369},
    {'deaths_pos': {},
     'ability_uses': {'centaur_double_edge': 1, 'centaur_hoof_stomp': 2},
     'ability_targets': {},
     'item_uses': {'tango': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 541,
     'healing': 0,
     'gold_delta': 324,
     'xp_delta': 430,
     'xp_start': 1256,
     'xp_end': 1686},
    {'deaths_pos': {},
     'ability_uses': {'oracle_purifying_flames': 3, 'oracle_fortunes_end': 1},
     'ability_targets': {},
     'item_uses': {'ward_dispenser': 1, 'blood_grenade': 1},
     'killed': {'npc_dota_hero_bristleback': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 697,
     'healing': 429,
     'gold_delta': 238,
     'xp_delta': 161,
     'xp_start': 757,
     'xp_end': 918},
    {'deaths_pos': {},
     'ability_uses': {'hoodwink_acorn_shot': 2, 'hoodwink_bushwhack': 2},
     'ability_targets': {},
     'item_uses': {'famango': 1, 'tango': 1, 'flask': 1, 'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 918,
     'healing': 215,
     'gold_delta': 73,
     'xp_delta': 161,
     'xp_start': 852,
     'xp_end': 1013},
    {'deaths_pos': {'166': {'100': 1}},
     'ability_uses': {'bristleback_quill_spray': 6},
     'ability_targets': {},
     'item_uses': {'magic_wand': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1444,
     'healing': 165,
     'gold_delta': 384,
     'xp_delta': 484,
     'xp_start': 1608,
     'xp_end': 2092},
    {'deaths_pos': {},
     'ability_uses': {'terrorblade_metamorphosis': 1,
      'terrorblade_conjure_image': 2},
     'ability_targets': {},
     'item_uses': {'power_treads': 11, 'magic_stick': 1, 'tango': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 560,
     'healing': 150,
     'gold_delta': 319,
     'xp_delta': 426,
     'xp_start': 1179,
     'xp_end': 1605},
    {'deaths_pos': {'128': {'132': 1}},
     'ability_uses': {'death_prophet_carrion_swarm': 2,
      'death_prophet_spirit_siphon': 1},
     'ability_targets': {},
     'item_uses': {'bottle': 1},
     'killed': {'npc_dota_hero_huskar': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 573,
     'healing': 375,
     'gold_delta': 465,
     'xp_delta': 564,
     'xp_start': 2345,
     'xp_end': 2909},
    {'deaths_pos': {},
     'ability_uses': {'ringmaster_impalement': 1},
     'ability_targets': {},
     'item_uses': {'ward_sentry': 1, 'tpscroll': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 39,
     'xp_delta': 202,
     'xp_start': 968,
     'xp_end': 1170},
    {'deaths_pos': {},
     'ability_uses': {'spirit_breaker_charge_of_darkness': 1},
     'ability_targets': {},
     'item_uses': {'ward_observer': 1,
      'magic_stick': 1,
      'famango': 1,
      'tango': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 296,
     'gold_delta': 193,
     'xp_delta': 202,
     'xp_start': 525,
     'xp_end': 727}]},
  {'start': 608,
   'end': 644,
   'last_death': 629,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'weaver_shukuchi': 5, 'weaver_the_swarm': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 11, 'magic_wand': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 928,
     'healing': 210,
     'gold_delta': 98,
     'xp_delta': 283,
     'xp_start': 4010,
     'xp_end': 4293},
    {'deaths_pos': {},
     'ability_uses': {'huskar_life_break': 1, 'huskar_inner_fire': 1},
     'ability_targets': {},
     'item_uses': {'armlet': 1, 'tpscroll': 1, 'magic_wand': 1},
     'killed': {'npc_dota_hero_death_prophet': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 4265,
     'healing': 225,
     'gold_delta': 287,
     'xp_delta': 367,
     'xp_start': 4442,
     'xp_end': 4809},
    {'deaths_pos': {'138': {'129': 1}},
     'ability_uses': {'centaur_stampede': 1,
      'centaur_double_edge': 2,
      'centaur_hoof_stomp': 2},
     'ability_targets': {},
     'item_uses': {'magic_stick': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 846,
     'healing': 150,
     'gold_delta': 250,
     'xp_delta': 371,
     'xp_start': 3180,
     'xp_end': 3551},
    {'deaths_pos': {},
     'ability_uses': {'oracle_fates_edict': 1,
      'oracle_purifying_flames': 4,
      'oracle_fortunes_end': 1},
     'ability_targets': {},
     'item_uses': {'clarity': 1, 'kobold_cup': 1},
     'killed': {'npc_dota_hero_spirit_breaker': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 697,
     'healing': 140,
     'gold_delta': 300,
     'xp_delta': 288,
     'xp_start': 1921,
     'xp_end': 2209},
    {'deaths_pos': {},
     'ability_uses': {'hoodwink_sharpshooter_release': 1,
      'hoodwink_acorn_shot': 1,
      'hoodwink_sharpshooter': 1,
      'hoodwink_bushwhack': 2},
     'ability_targets': {},
     'item_uses': {'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 593,
     'healing': 300,
     'gold_delta': 257,
     'xp_delta': 341,
     'xp_start': 2510,
     'xp_end': 2851},
    {'deaths_pos': {},
     'ability_uses': {'bristleback_viscous_nasal_goo': 3,
      'bristleback_quill_spray': 8},
     'ability_targets': {},
     'item_uses': {'power_treads': 15, 'tpscroll': 1, 'magic_wand': 1},
     'killed': {'npc_dota_hero_centaur': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 2395,
     'healing': 300,
     'gold_delta': 507,
     'xp_delta': 525,
     'xp_start': 4935,
     'xp_end': 5460},
    {'deaths_pos': {},
     'ability_uses': {'terrorblade_conjure_image': 3},
     'ability_targets': {},
     'item_uses': {'power_treads': 8, 'quelling_blade': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 282,
     'xp_delta': 274,
     'xp_start': 3978,
     'xp_end': 4252},
    {'deaths_pos': {'139': {'133': 1}},
     'ability_uses': {'death_prophet_carrion_swarm': 1,
      'death_prophet_spirit_siphon': 3},
     'ability_targets': {},
     'item_uses': {'magic_wand': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 325,
     'healing': 600,
     'gold_delta': -12,
     'xp_delta': 28,
     'xp_start': 3973,
     'xp_end': 4001},
    {'deaths_pos': {},
     'ability_uses': {'ringmaster_tame_the_beasts': 1,
      'ringmaster_the_box': 1,
      'ringmaster_impalement': 2,
      'ringmaster_strongman_tonic': 1},
     'ability_targets': {},
     'item_uses': {'ward_sentry': 1, 'magic_stick': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 462,
     'healing': 0,
     'gold_delta': 110,
     'xp_delta': 410,
     'xp_start': 2076,
     'xp_end': 2486},
    {'deaths_pos': {'143': {'136': 1}},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 201,
     'healing': 0,
     'gold_delta': 24,
     'xp_delta': 28,
     'xp_start': 1259,
     'xp_end': 1287}]},
  {'start': 1046,
   'end': 1099,
   'last_death': 1084,
   'deaths': 6,
   'players': [{'deaths_pos': {},
     'ability_uses': {'weaver_shukuchi': 8,
      'weaver_time_lapse': 1,
      'weaver_the_swarm': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 24, 'magic_wand': 2},
     'killed': {'npc_dota_hero_spirit_breaker': 1,
      'npc_dota_hero_ringmaster': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 2193,
     'healing': 345,
     'gold_delta': 695,
     'xp_delta': 1111,
     'xp_start': 9210,
     'xp_end': 10321},
    {'deaths_pos': {'136': {'101': 1}},
     'ability_uses': {'huskar_life_break': 1, 'huskar_inner_fire': 2},
     'ability_targets': {},
     'item_uses': {'armlet': 6, 'magic_wand': 2},
     'killed': {'npc_dota_hero_terrorblade': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 3571,
     'healing': 635,
     'gold_delta': 127,
     'xp_delta': 569,
     'xp_start': 9330,
     'xp_end': 9899},
    {'deaths_pos': {'142': {'119': 1}},
     'ability_uses': {'centaur_stampede': 1,
      'centaur_double_edge': 1,
      'centaur_hoof_stomp': 2},
     'ability_targets': {},
     'item_uses': {'magic_stick': 1, 'great_famango': 1, 'blink': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1298,
     'healing': 550,
     'gold_delta': 229,
     'xp_delta': 454,
     'xp_start': 6622,
     'xp_end': 7076},
    {'deaths_pos': {'162': {'90': 1}},
     'ability_uses': {'oracle_fates_edict': 1,
      'oracle_purifying_flames': 1,
      'oracle_fortunes_end': 1},
     'ability_targets': {},
     'item_uses': {'kobold_cup': 1, 'magic_wand': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 134,
     'healing': 859,
     'gold_delta': -92,
     'xp_delta': 0,
     'xp_start': 5107,
     'xp_end': 5107},
    {'deaths_pos': {},
     'ability_uses': {'hoodwink_sharpshooter_release': 1,
      'hoodwink_acorn_shot': 2,
      'hoodwink_scurry': 2,
      'hoodwink_sharpshooter': 1,
      'hoodwink_bushwhack': 2,
      'hoodwink_hunters_boomerang': 1},
     'ability_targets': {},
     'item_uses': {'arcane_boots': 1,
      'furion_gold_bag': 1,
      'foragers_mana': 1,
      'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1637,
     'healing': 244,
     'gold_delta': 230,
     'xp_delta': 569,
     'xp_start': 5560,
     'xp_end': 6129},
    {'deaths_pos': {},
     'ability_uses': {'bristleback_viscous_nasal_goo': 4,
      'bristleback_quill_spray': 12,
      'bristleback_hairball': 3},
     'ability_targets': {},
     'item_uses': {'power_treads': 28, 'mana_draught': 1, 'soul_ring': 1},
     'killed': {'npc_dota_hero_huskar': 1, 'npc_dota_hero_oracle': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 2995,
     'healing': 0,
     'gold_delta': 987,
     'xp_delta': 1664,
     'xp_start': 9778,
     'xp_end': 11442},
    {'deaths_pos': {'144': {'111': 1}},
     'ability_uses': {'terrorblade_sunder': 1,
      'terrorblade_metamorphosis': 1,
      'terrorblade_reflection': 1,
      'terrorblade_conjure_image': 2},
     'ability_targets': {},
     'item_uses': {'power_treads': 9, 'magic_wand': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 3650,
     'healing': 820,
     'gold_delta': 158,
     'xp_delta': 603,
     'xp_start': 7893,
     'xp_end': 8496},
    {'deaths_pos': {},
     'ability_uses': {'death_prophet_carrion_swarm': 5,
      'death_prophet_spirit_siphon': 3,
      'death_prophet_silence': 2,
      'death_prophet_exorcism': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 12, 'bottle': 2},
     'killed': {'npc_dota_hero_centaur': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 2157,
     'healing': 1076,
     'gold_delta': 768,
     'xp_delta': 1751,
     'xp_start': 6659,
     'xp_end': 8410},
    {'deaths_pos': {'157': {'99': 1}},
     'ability_uses': {'ringmaster_tame_the_beasts': 1,
      'ringmaster_impalement': 3,
      'ringmaster_wheel': 1},
     'ability_targets': {},
     'item_uses': {'ward_sentry': 1, 'tpscroll': 1, 'ward_dispenser': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 632,
     'healing': 0,
     'gold_delta': 149,
     'xp_delta': 0,
     'xp_start': 4402,
     'xp_end': 4402},
    {'deaths_pos': {'149': {'113': 1}},
     'ability_uses': {'spirit_breaker_bulldoze': 2,
      'spirit_breaker_nether_strike': 1,
      'spirit_breaker_charge_of_darkness': 1},
     'ability_targets': {},
     'item_uses': {'magic_stick': 1,
      'famango': 2,
      'phase_boots': 4,
      'medallion_of_courage': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 774,
     'healing': 280,
     'gold_delta': 56,
     'xp_delta': 40,
     'xp_start': 3603,
     'xp_end': 3643}]},
  {'start': 1329,
   'end': 1367,
   'last_death': 1352,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'weaver_shukuchi': 5, 'weaver_the_swarm': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 16, 'magic_wand': 1},
     'killed': {'npc_dota_hero_ringmaster': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 3012,
     'healing': 90,
     'gold_delta': 621,
     'xp_delta': 1771,
     'xp_start': 13724,
     'xp_end': 15495},
    {'deaths_pos': {},
     'ability_uses': {'huskar_life_break': 1, 'huskar_inner_fire': 2},
     'ability_targets': {},
     'item_uses': {},
     'killed': {'npc_dota_hero_bristleback': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 4138,
     'healing': 266,
     'gold_delta': 864,
     'xp_delta': 963,
     'xp_start': 12133,
     'xp_end': 13096},
    {'deaths_pos': {},
     'ability_uses': {'centaur_double_edge': 1, 'centaur_hoof_stomp': 1},
     'ability_targets': {},
     'item_uses': {'crimson_guard': 1, 'magic_stick': 2, 'blink': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 573,
     'healing': 165,
     'gold_delta': 340,
     'xp_delta': 1130,
     'xp_start': 8650,
     'xp_end': 9780},
    {'deaths_pos': {},
     'ability_uses': {'oracle_fates_edict': 2,
      'oracle_purifying_flames': 7,
      'oracle_fortunes_end': 3,
      'oracle_rain_of_destiny': 1},
     'ability_targets': {},
     'item_uses': {'blink': 1, 'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 863,
     'healing': 4726,
     'gold_delta': 191,
     'xp_delta': 807,
     'xp_start': 7244,
     'xp_end': 8051},
    {'deaths_pos': {},
     'ability_uses': {'hoodwink_acorn_shot': 2,
      'hoodwink_scurry': 2,
      'hoodwink_bushwhack': 2,
      'hoodwink_hunters_boomerang': 1},
     'ability_targets': {},
     'item_uses': {'arcane_boots': 1,
      'mana_draught': 1,
      'foragers_health': 2,
      'force_staff': 1,
      'magic_wand': 2},
     'killed': {'npc_dota_hero_death_prophet': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 774,
     'healing': 335,
     'gold_delta': 454,
     'xp_delta': 889,
     'xp_start': 8261,
     'xp_end': 9150},
    {'deaths_pos': {'116': {'125': 1}},
     'ability_uses': {'bristleback_viscous_nasal_goo': 2,
      'bristleback_quill_spray': 4,
      'bristleback_hairball': 2},
     'ability_targets': {},
     'item_uses': {'power_treads': 4},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 3569,
     'healing': 0,
     'gold_delta': -320,
     'xp_delta': 10,
     'xp_start': 14788,
     'xp_end': 14798},
    {'deaths_pos': {},
     'ability_uses': {'terrorblade_conjure_image': 2},
     'ability_targets': {},
     'item_uses': {'seeds_of_serenity': 1, 'power_treads': 3, 'manta': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 350,
     'healing': 0,
     'gold_delta': 145,
     'xp_delta': 181,
     'xp_start': 10755,
     'xp_end': 10936},
    {'deaths_pos': {'102': {'128': 1}},
     'ability_uses': {'death_prophet_carrion_swarm': 2,
      'death_prophet_spirit_siphon': 3,
      'death_prophet_silence': 1},
     'ability_targets': {},
     'item_uses': {'bottle': 2, 'magic_wand': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 2219,
     'healing': 628,
     'gold_delta': -238,
     'xp_delta': 20,
     'xp_start': 11255,
     'xp_end': 11275},
    {'deaths_pos': {'114': {'142': 1}},
     'ability_uses': {'ringmaster_tame_the_beasts': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1, 'ward_dispenser': 1, 'pogo_stick': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 155,
     'healing': 0,
     'gold_delta': -89,
     'xp_delta': 20,
     'xp_start': 5287,
     'xp_end': 5307},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1, 'phase_boots': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 0,
     'xp_delta': 0,
     'xp_start': 4716,
     'xp_end': 4716}]},
  {'start': 1872,
   'end': 1915,
   'last_death': 1900,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'weaver_shukuchi': 6, 'weaver_the_swarm': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 15, 'nullifier': 2},
     'killed': {'npc_dota_hero_terrorblade': 1,
      'npc_dota_hero_bristleback': 1,
      'npc_dota_hero_spirit_breaker': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1932,
     'healing': 0,
     'gold_delta': 1385,
     'xp_delta': 1517,
     'xp_start': 22758,
     'xp_end': 24275},
    {'deaths_pos': {},
     'ability_uses': {'huskar_life_break': 1, 'huskar_inner_fire': 1},
     'ability_targets': {},
     'item_uses': {'armlet': 3, 'hurricane_pike': 1, 'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 5059,
     'healing': 866,
     'gold_delta': 526,
     'xp_delta': 1405,
     'xp_start': 18653,
     'xp_end': 20058},
    {'deaths_pos': {},
     'ability_uses': {'centaur_double_edge': 3, 'centaur_hoof_stomp': 3},
     'ability_targets': {},
     'item_uses': {'jidi_pollen_bag': 1,
      'lotus_orb': 2,
      'magic_stick': 2,
      'blink': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 3172,
     'healing': 82,
     'gold_delta': 562,
     'xp_delta': 1405,
     'xp_start': 14347,
     'xp_end': 15752},
    {'deaths_pos': {},
     'ability_uses': {'oracle_fates_edict': 2,
      'oracle_purifying_flames': 7,
      'oracle_fortunes_end': 3,
      'oracle_rain_of_destiny': 1},
     'ability_targets': {},
     'item_uses': {'ghost': 1,
      'ward_dispenser': 3,
      'blink': 1,
      'magic_wand': 1,
      'glimmer_cape': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1633,
     'healing': 2443,
     'gold_delta': 528,
     'xp_delta': 1473,
     'xp_start': 11167,
     'xp_end': 12640},
    {'deaths_pos': {},
     'ability_uses': {'hoodwink_sharpshooter_release': 1,
      'hoodwink_acorn_shot': 2,
      'hoodwink_scurry': 5,
      'hoodwink_sharpshooter': 1,
      'hoodwink_bushwhack': 2,
      'hoodwink_hunters_boomerang': 1},
     'ability_targets': {},
     'item_uses': {'guardian_greaves': 1, 'magic_wand': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1561,
     'healing': 1645,
     'gold_delta': 369,
     'xp_delta': 1856,
     'xp_start': 15033,
     'xp_end': 16889},
    {'deaths_pos': {'114': {'112': 1}},
     'ability_uses': {'bristleback_viscous_nasal_goo': 1,
      'bristleback_quill_spray': 4,
      'bristleback_hairball': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 5},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1533,
     'healing': 0,
     'gold_delta': -257,
     'xp_delta': 67,
     'xp_start': 20464,
     'xp_end': 20531},
    {'deaths_pos': {'122': {'118': 1}},
     'ability_uses': {'terrorblade_sunder': 1,
      'terrorblade_conjure_image': 2,

In [7]:
query = 'SELECT * FROM hero_details'
heroes = db.query_select_to_df(query, table='hero_details')

In [100]:
match_wards

[{'match_id': 8760094725,
  'hero_id': 23,
  'time': 391,
  'type': 1,
  'positionX': 129.9,
  'positionY': 124.2},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': -58,
  'type': 0,
  'positionX': 126,
  'positionY': 155.4},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 445,
  'type': 0,
  'positionX': 192.3,
  'positionY': 85.3},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 750,
  'type': 0,
  'positionX': 155,
  'positionY': 73.7},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1223,
  'type': 0,
  'positionX': 136.1,
  'positionY': 155.7},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1247,
  'type': 0,
  'positionX': 164,
  'positionY': 133.8},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1341,
  'type': 0,
  'positionX': 142.1,
  'positionY': 169.9},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 35,
  'type': 1,
  'positionX': 95.5,
  'positionY': 164.1},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 445,
  'type': 1,
  'positionX': 192.2,
  'positionY': 85.4},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 636,
  'type': 1,
  'positionX': 83.2,
  'positionY': 159.3},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 742,
  'type': 1,
  'positionX': 152,
  'positionY': 73.2},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1017,
  'type': 1,
  'positionX': 172.7,
  'positionY': 141.6},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1057,
  'type': 1,
  'positionX': 190.8,
  'positionY': 133.6},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1069,
  'type': 1,
  'positionX': 176.5,
  'positionY': 116.6},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1220,
  'type': 1,
  'positionX': 136.4,
  'positionY': 155.9},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1237,
  'type': 1,
  'positionX': 138.8,
  'positionY': 134.5},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1340,
  'type': 1,
  'positionX': 143.2,
  'positionY': 169},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1353,
  'type': 1,
  'positionX': 162.2,
  'positionY': 140.5},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 117,
  'type': 0,
  'positionX': 151.8,
  'positionY': 89},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 287,
  'type': 0,
  'positionX': 149.1,
  'positionY': 82},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 509,
  'type': 0,
  'positionX': 154.1,
  'positionY': 129.7},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 536,
  'type': 0,
  'positionX': 134.1,
  'positionY': 112.2},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 687,
  'type': 0,
  'positionX': 134,
  'positionY': 78},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 915,
  'type': 0,
  'positionX': 163.8,
  'positionY': 133.9},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': -45,
  'type': 1,
  'positionX': 167.6,
  'positionY': 100.6},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 138,
  'type': 1,
  'positionX': 158.8,
  'positionY': 85.2},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 510,
  'type': 1,
  'positionX': 151.1,
  'positionY': 126.9},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 537,
  'type': 1,
  'positionX': 136.8,
  'positionY': 118.3},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 678,
  'type': 1,
  'positionX': 79,
  'positionY': 185.6},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 916,
  'type': 1,
  'positionX': 163.6,
  'positionY': 132.2},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': -9,
  'type': 0,
  'positionX': 144.3,
  'positionY': 88.7},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 558,
  'type': 0,
  'positionX': 163.8,
  'positionY': 134},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 1238,
  'type': 0,
  'positionX': 164.1,
  'positionY': 134},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 26,
  'type': 1,
  'positionX': 156.8,
  'positionY': 89.2},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 171,
  'type': 1,
  'positionX': 156.7,
  'positionY': 89.1},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 559,
  'type': 1,
  'positionX': 158.4,
  'positionY': 133.5},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 1240,
  'type': 1,
  'positionX': 166.9,
  'positionY': 136.6},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 1354,
  'type': 1,
  'positionX': 170.1,
  'positionY': 142.2},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 387,
  'type': 0,
  'positionX': 77,
  'positionY': 181.8},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 516,
  'type': 0,
  'positionX': 89.2,
  'positionY': 132.7},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 897,
  'type': 0,
  'positionX': 116.6,
  'positionY': 159.5},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 952,
  'type': 0,
  'positionX': 67,
  'positionY': 158.2},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 1398,
  'type': 0,
  'positionX': 178.2,
  'positionY': 166.5},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 52,
  'type': 1,
  'positionX': 96.9,
  'positionY': 170.2},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 355,
  'type': 1,
  'positionX': 94.4,
  'positionY': 167.3},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 499,
  'type': 1,
  'positionX': 82.9,
  'positionY': 161.8},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 508,
  'type': 1,
  'positionX': 86.3,
  'positionY': 147},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 862,
  'type': 1,
  'positionX': 150.8,
  'positionY': 125.2},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 872,
  'type': 1,
  'positionX': 147.5,
  'positionY': 138.7},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 886,
  'type': 1,
  'positionX': 140.5,
  'positionY': 153.4},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 894,
  'type': 1,
  'positionX': 121.7,
  'positionY': 159.1},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 901,
  'type': 1,
  'positionX': 106.9,
  'positionY': 161.9},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 906,
  'type': 1,
  'positionX': 90.5,
  'positionY': 163.3},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 1309,
  'type': 1,
  'positionX': 170.5,
  'positionY': 151.8},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 1322,
  'type': 1,
  'positionX': 175.7,
  'positionY': 139.1},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 1340,
  'type': 1,
  'positionX': 154.1,
  'positionY': 162.5},
 {'match_id': 8760094725,
  'hero_id': 38,
  'time': 642,
  'type': 1,
  'positionX': 168.5,
  'positionY': 97.9},
 {'match_id': 8760094725,
  'hero_id': 96,
  'time': -31,
  'type': 0,
  'positionX': 126.1,
  'positionY': 120.3},
 {'match_id': 8760094725,
  'hero_id': 96,
  'time': 317,
  'type': 0,
  'positionX': 129.8,
  'positionY': 126.2}]

In [ ]:
match_death_events = []
mid = result['match_id']
for p in result['players']:
    hero_id = p['hero_id']
    for kill in p['kills_log']:
        match_death_events.append(
            {
                'match_id': mid,
                'hero_id': int(heroes[heroes['name'] == kill['key']].get('id').iloc[0]),
                'time': kill['time'],
                'attacker': hero_id
            }
        )

In [99]:
pd.DataFrame(match_details, index=[0])

,id,tournamentId,tournamentRound,leagueId,radiantTeamId,direTeamId,seriesId,clusterId,didRadiantWin,startDateTime,...,towerStatusRadiant,towerStatusDire,barracksStatusRadiant,barracksStatusDire,rank,actualRank,averageRank,averageImp,radiant_score,dire_score
0,8760126026,None,None,18866,8680909,9872558,1083445,272,True,1775466314,...,1846,0,63,0,None,None,None,None,34,8

In [88]:
match_details = {
    'id': result['match_id'],
    'tournamentId': result.get('tournament_id'),
    'tournamentRound': result.get('tournament_round'),
    'leagueId': result['leagueid'],
    'radiantTeamId': result['radiant_team_id'], 
    'direTeamId': result['dire_team_id'],
    'seriesId': result['series_id'],
    'clusterId': result['cluster'],
    'didRadiantWin': result['radiant_win'],
    'startDateTime': result['start_time'],
    'endDateTime': result['start_time'] + result['duration'],
    'durationSeconds': result['duration'],
    'firstBloodTime': result['first_blood_time'],
    'towerStatusRadiant': result['tower_status_radiant'],
    'towerStatusDire': result['tower_status_dire'],
    'barracksStatusRadiant': result['barracks_status_radiant'],
    'barracksStatusDire': result['barracks_status_dire'],
    'rank': result.get('rank_tier'),
    'actualRank': result.get('rank_tier_actual'),
    'averageRank': result.get('average_rank'),
    'averageImp': result.get('average_imp'),
    'radiant_score': result['radiant_score'],
    'dire_score': result['dire_score']
}

In [ ]:
match_pick_bans = []
mid = result['match_id']
for mpb in result['picks_bans']:
    match_pick_bans.append(
        {
            'match_id': mid,
            'isPick': mpb['is_pick'],
            'heroId': mpb['hero_id'],
            'order': mpb['order'],
            'isRadiant': mpb['team'] == 0
        }
    )

In [ ]:
match_players = []
mid = result['match_id']
for p in result['players']:
    is_radiant = p['team_number'] == 0
    if (is_radiant and p['team_number'] == 0) or (not is_radiant and p['team_number'] == 1):
        is_victory = True
    else:
        is_victory = False           
    match_players.append(
        {
            'match_id': mid,
            'heroId': p['hero_id'],
            'isRadiant': is_radiant,
            'isVictory': is_victory,
            'variant': p['hero_variant'],
            'networth': p['net_worth'],
            'goldPerMinute': p['gold_per_min'],
            'goldSpent': p['gold_spent'],
            'towerDamage': p['tower_damage'],
            'heroDamage': p['hero_damage'],
            'steamAccountId': p['account_id'],
            'partyId': p['party_id'],
            'name': p['name'],
            'kills': p['kills'],
            'deaths': p['deaths'],
            'assists': p['assists']
        }
    )

In [56]:
query = 'SELECT * FROM item_details_opendota'
items = db.query_select_to_df(query, table='item_details_opendota')

In [ ]:
match_purchases = []
mid = result['match_id']
for p in result['players']:
    hero_id = p['hero_id']
    for pur in p['purchase_log']:
        match_purchases.append(
            {
                'match_id': mid,
                'hero_id': hero_id,
                'time': pur['time'],
                'itemId': items[items['shortName'] == pur['key']].get('id').iloc[0]
            }
        )

In [ ]:
rune_map = {
    "0": "DOUBLE_DAMAGE",
    "1": "HASTE",
    "2": "ILLUSION",
    "3": "INVISIBILITY",
    "4": "REGEN",
    "5": "BOUNTY",
    "6": "ARCANE",
    "7": "WATER",
    "8": "WISDOM",
    "9": "SHIELD"
}
match_runes = []
mid = result['match_id']
for p in result['players']:
    for rune in p['runes_log']:
        match_runes.append(
            {
                'match_id': mid,
                'hero_id': p['hero_id'],
                'time': rune['time'],
                'rune': rune_map[rune['key']]
            }
        )

In [66]:
query = 'SELECT * FROM npcs'
npcs = db.query_select_to_df(query, table='npcs')

In [71]:
obj

{'time': 674,
 'type': 'building_kill',
 'unit': 'npc_dota_creep_badguys_melee',
 'key': 'npc_dota_goodguys_tower1_bot'}

In [87]:
match_tower_deaths = []
mid = result['match_id']
for obj in result['objectives']:
    if obj['type'] == 'building_kill':
        try:
            attacker = heroes[heroes['name'] == obj['unit']].get('id').iloc[0]
        except:
            attacker = 'non-hero'
        match_tower_deaths.append(
            {
                'match_id': mid,
                'time': obj['time'],
                'npcId': npcs[npcs['name'] == obj['key']].get('id').iloc[0],
                'isRadiant': 'goodguys' in obj['key'],
                'attacker': attacker
            }
        )

In [ ]:
match_wards = []
for p in result['players']:
    for ward in p['obs_log']:
        match_wards.append(
            {
                'match_id': mid,
                'hero_id': p['hero_id'],
                'time': ward['time'],
                'type': 0,
                'positionX': ward['x'],
                'positionY': ward['y']
            }
        )
    for ward in p['sen_log']:
        match_wards.append(
            {
                'match_id': mid,
                'hero_id': p['hero_id'],
                'time': ward['time'],
                'type': 1,
                'positionX': ward['x'],
                'positionY': ward['y']
            }
        )

In [77]:
match_wards

[{'match_id': 8760094725,
  'hero_id': 23,
  'time': 391,
  'type': 1,
  'positionX': 129.9,
  'positionY': 124.2},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': -58,
  'type': 0,
  'positionX': 126,
  'positionY': 155.4},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 445,
  'type': 0,
  'positionX': 192.3,
  'positionY': 85.3},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 750,
  'type': 0,
  'positionX': 155,
  'positionY': 73.7},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1223,
  'type': 0,
  'positionX': 136.1,
  'positionY': 155.7},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1247,
  'type': 0,
  'positionX': 164,
  'positionY': 133.8},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1341,
  'type': 0,
  'positionX': 142.1,
  'positionY': 169.9},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 35,
  'type': 1,
  'positionX': 95.5,
  'positionY': 164.1},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 445,
  'type': 1,
  'positionX': 192.2,
  'positionY': 85.4},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 636,
  'type': 1,
  'positionX': 83.2,
  'positionY': 159.3},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 742,
  'type': 1,
  'positionX': 152,
  'positionY': 73.2},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1017,
  'type': 1,
  'positionX': 172.7,
  'positionY': 141.6},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1057,
  'type': 1,
  'positionX': 190.8,
  'positionY': 133.6},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1069,
  'type': 1,
  'positionX': 176.5,
  'positionY': 116.6},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1220,
  'type': 1,
  'positionX': 136.4,
  'positionY': 155.9},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1237,
  'type': 1,
  'positionX': 138.8,
  'positionY': 134.5},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1340,
  'type': 1,
  'positionX': 143.2,
  'positionY': 169},
 {'match_id': 8760094725,
  'hero_id': 88,
  'time': 1353,
  'type': 1,
  'positionX': 162.2,
  'positionY': 140.5},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 117,
  'type': 0,
  'positionX': 151.8,
  'positionY': 89},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 287,
  'type': 0,
  'positionX': 149.1,
  'positionY': 82},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 509,
  'type': 0,
  'positionX': 154.1,
  'positionY': 129.7},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 536,
  'type': 0,
  'positionX': 134.1,
  'positionY': 112.2},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 687,
  'type': 0,
  'positionX': 134,
  'positionY': 78},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 915,
  'type': 0,
  'positionX': 163.8,
  'positionY': 133.9},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': -45,
  'type': 1,
  'positionX': 167.6,
  'positionY': 100.6},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 138,
  'type': 1,
  'positionX': 158.8,
  'positionY': 85.2},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 510,
  'type': 1,
  'positionX': 151.1,
  'positionY': 126.9},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 537,
  'type': 1,
  'positionX': 136.8,
  'positionY': 118.3},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 678,
  'type': 1,
  'positionX': 79,
  'positionY': 185.6},
 {'match_id': 8760094725,
  'hero_id': 64,
  'time': 916,
  'type': 1,
  'positionX': 163.6,
  'positionY': 132.2},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': -9,
  'type': 0,
  'positionX': 144.3,
  'positionY': 88.7},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 558,
  'type': 0,
  'positionX': 163.8,
  'positionY': 134},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 1238,
  'type': 0,
  'positionX': 164.1,
  'positionY': 134},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 26,
  'type': 1,
  'positionX': 156.8,
  'positionY': 89.2},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 171,
  'type': 1,
  'positionX': 156.7,
  'positionY': 89.1},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 559,
  'type': 1,
  'positionX': 158.4,
  'positionY': 133.5},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 1240,
  'type': 1,
  'positionX': 166.9,
  'positionY': 136.6},
 {'match_id': 8760094725,
  'hero_id': 101,
  'time': 1354,
  'type': 1,
  'positionX': 170.1,
  'positionY': 142.2},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 387,
  'type': 0,
  'positionX': 77,
  'positionY': 181.8},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 516,
  'type': 0,
  'positionX': 89.2,
  'positionY': 132.7},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 897,
  'type': 0,
  'positionX': 116.6,
  'positionY': 159.5},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 952,
  'type': 0,
  'positionX': 67,
  'positionY': 158.2},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 1398,
  'type': 0,
  'positionX': 178.2,
  'positionY': 166.5},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 52,
  'type': 1,
  'positionX': 96.9,
  'positionY': 170.2},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 355,
  'type': 1,
  'positionX': 94.4,
  'positionY': 167.3},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 499,
  'type': 1,
  'positionX': 82.9,
  'positionY': 161.8},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 508,
  'type': 1,
  'positionX': 86.3,
  'positionY': 147},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 862,
  'type': 1,
  'positionX': 150.8,
  'positionY': 125.2},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 872,
  'type': 1,
  'positionX': 147.5,
  'positionY': 138.7},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 886,
  'type': 1,
  'positionX': 140.5,
  'positionY': 153.4},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 894,
  'type': 1,
  'positionX': 121.7,
  'positionY': 159.1},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 901,
  'type': 1,
  'positionX': 106.9,
  'positionY': 161.9},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 906,
  'type': 1,
  'positionX': 90.5,
  'positionY': 163.3},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 1309,
  'type': 1,
  'positionX': 170.5,
  'positionY': 151.8},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 1322,
  'type': 1,
  'positionX': 175.7,
  'positionY': 139.1},
 {'match_id': 8760094725,
  'hero_id': 40,
  'time': 1340,
  'type': 1,
  'positionX': 154.1,
  'positionY': 162.5},
 {'match_id': 8760094725,
  'hero_id': 38,
  'time': 642,
  'type': 1,
  'positionX': 168.5,
  'positionY': 97.9},
 {'match_id': 8760094725,
  'hero_id': 96,
  'time': -31,
  'type': 0,
  'positionX': 126.1,
  'positionY': 120.3},
 {'match_id': 8760094725,
  'hero_id': 96,
  'time': 317,
  'type': 0,
  'positionX': 129.8,
  'positionY': 126.2}]

In [ ]:
result

{'version': 22,
 'match_id': 8760094725,
 'teamfights': [{'start': -15,
   'end': 20,
   'last_death': 5,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'dawnbreaker_converge': 1,
      'dawnbreaker_celestial_hammer': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 279,
     'healing': 0,
     'gold_delta': 110,
     'xp_delta': 25},
    {'deaths_pos': {'138': {'100': 1}},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1,
      'magic_stick': 1,
      'quelling_blade': 2,
      'faerie_fire': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 363,
     'healing': 194,
     'gold_delta': 95,
     'xp_delta': 25},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 80,
     'xp_delta': 0},
    {'deaths_pos': {'139': {'105': 1}},
     'ability_uses': {'nyx_assassin_impale': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1, 'blood_grenade': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 334,
     'healing': 0,
     'gold_delta': 94,
     'xp_delta': 25},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {'blood_grenade': 1},
     'killed': {'npc_dota_hero_centaur': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 550,
     'healing': 0,
     'gold_delta': 378,
     'xp_delta': 25},
    {'deaths_pos': {},
     'ability_uses': {'skywrath_mage_concussive_shot': 1,
      'ability_lamp_use': 1},
     'ability_targets': {},
     'item_uses': {'ward_dispenser': 1, 'blood_grenade': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 509,
     'healing': 0,
     'gold_delta': 147,
     'xp_delta': 69},
    {'deaths_pos': {},
     'ability_uses': {'venomancer_venomous_gale': 1},
     'ability_targets': {},
     'item_uses': {'blood_grenade': 1},
     'killed': {'npc_dota_hero_nyx_assassin': 1,
      'npc_dota_hero_life_stealer': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 723,
     'healing': 0,
     'gold_delta': 413,
     'xp_delta': 69},
    {'deaths_pos': {},
     'ability_uses': {'beastmaster_summon_razorback': 2},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 387,
     'healing': 0,
     'gold_delta': 147,
     'xp_delta': 69},
    {'deaths_pos': {'139': {'101': 1}},
     'ability_uses': {'centaur_hoof_stomp': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 315,
     'healing': 0,
     'gold_delta': 131,
     'xp_delta': 0},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 80,
     'xp_delta': 0}]},
  {'start': 262,
   'end': 303,
   'last_death': 288,
   'deaths': 3,
   'players': [{'deaths_pos': {'76': {'152': 1}},
     'ability_uses': {'dawnbreaker_converge': 1,
      'dawnbreaker_celestial_hammer': 1,
      'dawnbreaker_fire_wreath': 1},
     'ability_targets': {},
     'item_uses': {'magic_stick': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 684,
     'healing': 165,
     'gold_delta': -42,
     'xp_delta': 60,
     'xp_start': 1332,
     'xp_end': 1392},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 97,
     'gold_delta': 153,
     'xp_delta': 293,
     'xp_start': 923,
     'xp_end': 1216},
    {'deaths_pos': {},
     'ability_uses': {'kunkka_return': 1,
      'kunkka_torrent': 1,
      'kunkka_x_marks_the_spot': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 768,
     'healing': 111,
     'gold_delta': 686,
     'xp_delta': 819,
     'xp_start': 1927,
     'xp_end': 2746},
    {'deaths_pos': {},
     'ability_uses': {'nyx_assassin_spiked_carapace': 1,
      'nyx_assassin_impale': 1},
     'ability_targets': {},
     'item_uses': {'blood_grenade': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 376,
     'healing': 0,
     'gold_delta': 0,
     'xp_delta': 0,
     'xp_start': 290,
     'xp_end': 290},
    {'deaths_pos': {'148': {'81': 1}},
     'ability_uses': {'jakiro_dual_breath': 2},
     'ability_targets': {},
     'item_uses': {'ward_observer': 1,
      'famango': 1,
      'faerie_fire': 1,
      'magic_wand': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 491,
     'healing': 270,
     'gold_delta': -25,
     'xp_delta': 56,
     'xp_start': 687,
     'xp_end': 743},
    {'deaths_pos': {},
     'ability_uses': {'skywrath_mage_arcane_bolt': 2,
      'skywrath_mage_concussive_shot': 2},
     'ability_targets': {},
     'item_uses': {'clarity': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 629,
     'healing': 0,
     'gold_delta': 52,
     'xp_delta': 163,
     'xp_start': 593,
     'xp_end': 756},
    {'deaths_pos': {},
     'ability_uses': {'venomancer_venomous_gale': 1,
      'venomancer_snakebite': 1,
      'venomancer_plague_ward': 2},
     'ability_targets': {},
     'item_uses': {'urn_of_shadows': 2},
     'killed': {'npc_dota_hero_dawnbreaker': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 942,
     'healing': 237,
     'gold_delta': 223,
     'xp_delta': 258,
     'xp_start': 790,
     'xp_end': 1048},
    {'deaths_pos': {},
     'ability_uses': {'beastmaster_wild_axes': 2,
      'beastmaster_summon_razorback': 1},
     'ability_targets': {},
     'item_uses': {'madstone_bundle': 1,
      'clarity': 1,
      'tango': 1,
      'branches': 1},
     'killed': {'npc_dota_hero_jakiro': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 533,
     'healing': 160,
     'gold_delta': 306,
     'xp_delta': 359,
     'xp_start': 1511,
     'xp_end': 1870},
    {'deaths_pos': {'122': {'125': 1}},
     'ability_uses': {'centaur_double_edge': 1, 'centaur_hoof_stomp': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 514,
     'healing': 0,
     'gold_delta': -1,
     'xp_delta': 69,
     'xp_start': 1753,
     'xp_end': 1822},
    {'deaths_pos': {},
     'ability_uses': {'luna_lucent_beam': 1},
     'ability_targets': {},
     'item_uses': {'famango': 1, 'faerie_fire': 1, 'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 576,
     'healing': 360,
     'gold_delta': 190,
     'xp_delta': 384,
     'xp_start': 1158,
     'xp_end': 1542}]},
  {'start': 567,
   'end': 604,
   'last_death': 589,
   'deaths': 5,
   'players': [{'deaths_pos': {},
     'ability_uses': {'dawnbreaker_converge': 2,
      'dawnbreaker_celestial_hammer': 2,
      'dawnbreaker_fire_wreath': 1},
     'ability_targets': {},
     'item_uses': {'magic_stick': 1, 'soul_ring': 1, 'flask': 1},
     'killed': {'npc_dota_hero_skywrath_mage': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 738,
     'healing': 212,
     'gold_delta': 317,
     'xp_delta': 567,
     'xp_start': 3715,
     'xp_end': 4282},
    {'deaths_pos': {},
     'ability_uses': {'life_stealer_open_wounds': 1},
     'ability_targets': {},
     'item_uses': {'quelling_blade': 3, 'phase_boots': 4},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 36,
     'gold_delta': 264,
     'xp_delta': 532,
     'xp_start': 3326,
     'xp_end': 3858},
    {'deaths_pos': {},
     'ability_uses': {'kunkka_torrent': 1, 'kunkka_x_marks_the_spot': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5, 'magic_wand': 2},
     'killed': {'npc_dota_hero_centaur': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1102,
     'healing': 135,
     'gold_delta': 390,
     'xp_delta': 477,
     'xp_start': 5088,
     'xp_end': 5565},
    {'deaths_pos': {'180': {'99': 1}},
     'ability_uses': {'nyx_assassin_spiked_carapace': 1,
      'nyx_assassin_impale': 1},
     'ability_targets': {},
     'item_uses': {'magic_stick': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 707,
     'healing': 120,
     'gold_delta': 137,
     'xp_delta': 182,
     'xp_start': 1818,
     'xp_end': 2000},
    {'deaths_pos': {'174': {'103': 1}},
     'ability_uses': {'jakiro_dual_breath': 2},
     'ability_targets': {},
     'item_uses': {'enchanted_mango': 1, 'magic_wand': 1},
     'killed': {'npc_dota_hero_venomancer': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 948,
     'healing': 121,
     'gold_delta': 238,
     'xp_delta': 182,
     'xp_start': 1941,
     'xp_end': 2123},
    {'deaths_pos': {'175': {'105': 1}},
     'ability_uses': {'skywrath_mage_arcane_bolt': 2,
      'skywrath_mage_concussive_shot': 1,
      'skywrath_mage_ancient_seal': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 375,
     'healing': 0,
     'gold_delta': 47,
     'xp_delta': 735,
     'xp_start': 2018,
     'xp_end': 2753},
    {'deaths_pos': {'180': {'104': 1}},
     'ability_uses': {'venomancer_venomous_gale': 1,
      'venomancer_snakebite': 1,
      'venomancer_plague_ward': 3},
     'ability_targets': {},
     'item_uses': {'famango': 1, 'urn_of_shadows': 1, 'faerie_fire': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1174,
     'healing': 210,
     'gold_delta': 47,
     'xp_delta': 0,
     'xp_start': 2033,
     'xp_end': 2033},
    {'deaths_pos': {},
     'ability_uses': {'beastmaster_summon_razorback': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {'npc_dota_hero_nyx_assassin': 1, 'npc_dota_hero_jakiro': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 326,
     'healing': 0,
     'gold_delta': 427,
     'xp_delta': 0,
     'xp_start': 3668,
     'xp_end': 3668},
    {'deaths_pos': {'186': {'111': 1}},
     'ability_uses': {'centaur_hoof_stomp': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 204,
     'healing': 0,
     'gold_delta': -40,
     'xp_delta': 0,
     'xp_start': 3566,
     'xp_end': 3566},
    {'deaths_pos': {},
     'ability_uses': {'luna_lucent_beam': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 3, 'tpscroll': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 243,
     'healing': 188,
     'gold_delta': 270,
     'xp_delta': 467,
     'xp_start': 3696,
     'xp_end': 4163}]},
  {'start': 685,
   'end': 729,
   'last_death': 714,
   'deaths': 3,
   'players': [{'deaths_pos': {'163': {'92': 1}},
     'ability_uses': {'dawnbreaker_solar_guardian': 1,
      'dawnbreaker_celestial_hammer': 1,
      'dawnbreaker_fire_wreath': 1},
     'ability_targets': {},
     'item_uses': {'magic_stick': 1, 'soul_ring': 1, 'phase_boots': 3},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 580,
     'healing': 255,
     'gold_delta': 80,
     'xp_delta': 230,
     'xp_start': 5159,
     'xp_end': 5389},
    {'deaths_pos': {},
     'ability_uses': {'life_stealer_infest': 1, 'life_stealer_consume': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 108,
     'healing': 150,
     'gold_delta': 164,
     'xp_delta': 231,
     'xp_start': 4538,
     'xp_end': 4769},
    {'deaths_pos': {},
     'ability_uses': {'kunkka_return': 1,
      'kunkka_torrent': 1,
      'kunkka_x_marks_the_spot': 2,
      'kunkka_ghostship': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5, 'magic_wand': 1},
     'killed': {'npc_dota_hero_luna': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1704,
     'healing': 15,
     'gold_delta': 626,
     'xp_delta': 1082,
     'xp_start': 6678,
     'xp_end': 7760},
    {'deaths_pos': {'170': {'96': 1}},
     'ability_uses': {'nyx_assassin_vendetta': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': -63,
     'xp_delta': 5,
     'xp_start': 2622,
     'xp_end': 2627},
    {'deaths_pos': {},
     'ability_uses': {'jakiro_dual_breath': 2},
     'ability_targets': {},
     'item_uses': {'ward_observer': 1, 'magic_wand': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 506,
     'healing': 45,
     'gold_delta': 26,
     'xp_delta': 226,
     'xp_start': 2537,
     'xp_end': 2763},
    {'deaths_pos': {},
     'ability_uses': {'skywrath_mage_arcane_bolt': 4,
      'skywrath_mage_concussive_shot': 2,
      'skywrath_mage_mystic_flare': 1,
      'skywrath_mage_ancient_seal': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1, 'blood_grenade': 1},
     'killed': {'npc_dota_hero_dawnbreaker': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 943,
     'healing': 0,
     'gold_delta': 355,
     'xp_delta': 502,
     'xp_start': 3109,
     'xp_end': 3611},
    {'deaths_pos': {},
     'ability_uses': {'venomancer_venomous_gale': 1,
      'venomancer_snakebite': 1,
      'venomancer_plague_ward': 6,
      'venomancer_noxious_plague': 1},
     'ability_targets': {},
     'item_uses': {'arcane_boots': 1, 'urn_of_shadows': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 749,
     'healing': 0,
     'gold_delta': 196,
     'xp_delta': 502,
     'xp_start': 2487,
     'xp_end': 2989},
    {'deaths_pos': {},
     'ability_uses': {'beastmaster_wild_axes': 4,
      'beastmaster_primal_roar': 1,
      'beastmaster_summon_razorback': 2},
     'ability_targets': {},
     'item_uses': {'helm_of_the_dominator': 1},
     'killed': {'npc_dota_hero_nyx_assassin': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1076,
     'healing': 0,
     'gold_delta': 554,
     'xp_delta': 647,
     'xp_start': 4219,
     'xp_end': 4866},
    {'deaths_pos': {},
     'ability_uses': {'centaur_stampede': 1, 'centaur_double_edge': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 231,
     'healing': 0,
     'gold_delta': 210,
     'xp_delta': 623,
     'xp_start': 4114,
     'xp_end': 4737},
    {'deaths_pos': {'96': {'158': 1}},
     'ability_uses': {'luna_eclipse': 1, 'luna_lucent_beam': 1},
     'ability_targets': {},
     'item_uses': {'power_treads': 2, 'magic_wand': 1, 'mask_of_madness': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1455,
     'healing': 205,
     'gold_delta': -141,
     'xp_delta': 51,
     'xp_start': 5337,
     'xp_end': 5388}]},
  {'start': 840,
   'end': 876,
   'last_death': 861,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'dawnbreaker_converge': 2,
      'dawnbreaker_solar_guardian': 1,
      'dawnbreaker_celestial_hammer': 2,
      'dawnbreaker_fire_wreath': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 3},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1623,
     'healing': 1103,
     'gold_delta': 454,
     'xp_delta': 593,
     'xp_start': 6811,
     'xp_end': 7404},
    {'deaths_pos': {},
     'ability_uses': {'life_stealer_infest': 1,
      'life_stealer_consume': 1,
      'life_stealer_rage': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1, 'quelling_blade': 3, 'phase_boots': 4},
     'killed': {'npc_dota_hero_skywrath_mage': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 177,
     'healing': 102,
     'gold_delta': 385,
     'xp_delta': 635,
     'xp_start': 5882,
     'xp_end': 6517},
    {'deaths_pos': {},
     'ability_uses': {'kunkka_return': 2,
      'kunkka_torrent': 2,
      'kunkka_x_marks_the_spot': 2},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5, 'blade_mail': 1, 'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1698,
     'healing': 180,
     'gold_delta': 384,
     'xp_delta': 593,
     'xp_start': 9349,
     'xp_end': 9942},
    {'deaths_pos': {},
     'ability_uses': {'nyx_assassin_spiked_carapace': 1,
      'nyx_assassin_impale': 2,
      'nyx_assassin_vendetta': 1},
     'ability_targets': {},
     'item_uses': {'magic_stick': 2},
     'killed': {'npc_dota_hero_beastmaster': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 514,
     'healing': 135,
     'gold_delta': 479,
     'xp_delta': 608,
     'xp_start': 3587,
     'xp_end': 4195},
    {'deaths_pos': {},
     'ability_uses': {'jakiro_ice_path': 1,
      'jakiro_dual_breath': 1,
      'jakiro_macropyre': 1},
     'ability_targets': {},
     'item_uses': {'arcane_boots': 1,
      'tpscroll': 1,
      'kobold_cup': 1,
      'quelling_blade': 1,
      'magic_wand': 1},
     'killed': {'npc_dota_hero_centaur': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 477,
     'healing': 0,
     'gold_delta': 430,
     'xp_delta': 593,
     'xp_start': 3401,
     'xp_end': 3994},
    {'deaths_pos': {'138': {'124': 1}},
     'ability_uses': {'skywrath_mage_arcane_bolt': 4,
      'skywrath_mage_concussive_shot': 2,
      'skywrath_mage_ancient_seal': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1167,
     'healing': 0,
     'gold_delta': -76,
     'xp_delta': 57,
     'xp_start': 4087,
     'xp_end': 4144},
    {'deaths_pos': {},
     'ability_uses': {'venomancer_venomous_gale': 1,
      'venomancer_plague_ward': 4},
     'ability_targets': {},
     'item_uses': {'arcane_boots': 1, 'ward_dispenser': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 340,
     'healing': 0,
     'gold_delta': 0,
     'xp_delta': 0,
     'xp_start': 3189,
     'xp_end': 3189},
    {'deaths_pos': {'136': {'116': 1}},
     'ability_uses': {'beastmaster_wild_axes': 1,
      'beastmaster_primal_roar': 1,
      'beastmaster_summon_razorback': 1},
     'ability_targets': {},
     'item_uses': {'polliwog_charm': 1, 'famango': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1479,
     'healing': 125,
     'gold_delta': -153,
     'xp_delta': 0,
     'xp_start': 5669,
     'xp_end': 5669},
    {'deaths_pos': {'134': {'116': 1}},
     'ability_uses': {'centaur_double_edge': 2, 'centaur_hoof_stomp': 1},
     'ability_targets': {},
     'item_uses': {'blink': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1647,
     'healing': 0,
     'gold_delta': -127,
     'xp_delta': 0,
     'xp_start': 5470,
     'xp_end': 5470},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {'mask_of_madness': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 215,
     'gold_delta': 427,
     'xp_delta': 734,
     'xp_start': 7288,
     'xp_end': 7986}]},
  {'start': 1015,
   'end': 1068,
   'last_death': 1053,
   'deaths': 4,
   'players': [{'deaths_pos': {},
     'ability_uses': {'dawnbreaker_converge': 4,
      'dawnbreaker_celestial_hammer': 3,
      'dawnbreaker_fire_wreath': 3},
     'ability_targets': {},
     'item_uses': {'madstone_bundle': 1,
      'magic_stick': 2,
      'soul_ring': 1,
      'phase_boots': 5},
     'killed': {'npc_dota_hero_centaur': 1,
      'npc_dota_hero_luna': 1,
      'npc_dota_hero_beastmaster': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1500,
     'healing': 1784,
     'gold_delta': 1405,

In [15]:
with httpx.Client() as client:
    schema = db.query_opendota(client, endpoint='schema')